python perceptron.py ../data/train.db ../data/test.db 10 0.1
python perceptron.py ../data/train.db ../data/test.db 10 0.2
python perceptron.py ../data/train.db ../data/test.db 10 0.3
python perceptron.py ../data/train.db ../data/test.db 10 0.4
python perceptron.py ../data/train.db ../data/test.db 10 0.5
python perceptron.py ../data/train.db ../data/test.db 10 0.6
python perceptron.py ../data/train.db ../data/test.db 10 0.7
python perceptron.py ../data/train.db ../data/test.db 10 0.8
python perceptron.py ../data/train.db ../data/test.db 10 0.9
python perceptron.py ../data/train.db ../data/test.db 10 1.0
