python perceptron.py ../../data/train.db ../data/test.db 50 0.1
python perceptron.py ../../data/train.db ../data/test.db 50 0.2
python perceptron.py ../../data/train.db ../data/test.db 50 0.3
python perceptron.py ../../data/train.db ../data/test.db 50 0.4
python perceptron.py ../../data/train.db ../data/test.db 50 0.5
python perceptron.py ../../data/train.db ../data/test.db 50 0.6
python perceptron.py ../../data/train.db ../data/test.db 50 0.7
python perceptron.py ../../data/train.db ../data/test.db 50 0.8
python perceptron.py ../../data/train.db ../data/test.db 50 0.9
python perceptron.py ../../data/train.db ../data/test.db 50 1.0
